"""Make Admin navigation use the exact same idle-card styling path as Work Management.

This build-time patch does not copy or approximate colors. It rewrites the Admin
navigation generated by mobile_nav_patch.py so each Admin button uses the same
`ops_alert_idle_*` container key and the same Streamlit secondary-button type as
idle Work Management cards. The existing shared CSS therefore styles both from
the exact same rule, including background, border, text, shadow and hover state.
"""
from pathlib import Path


def _replace_required(text: str, variants, replacement: str, label: str) -> str:
    for old in variants:
        if old in text:
            return text.replace(old, replacement, 1)
    raise RuntimeError(f"KHDN exact Admin-style patch cannot find: {label}")


def install():
    patch_file = Path(__file__).resolve().parent / "mobile_nav_patch.py"
    text = patch_file.read_text(encoding="utf-8")
    text = _replace_required(
        text,
        ['admin_nav_card_{_idx}'],
        'ops_alert_idle_admin_view_{_idx}',
        "Admin idle container key",
    )
    text = _replace_required(
        text,
        [
            'type=\"primary\" if _admin_current==_value else \"secondary\"',
            'type="primary" if _admin_current==_value else "secondary"',
        ],
        'type=\"secondary\"',
        "Admin secondary button type",
    )
    patch_file.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    install()
