[build]
builder = "DOCKERFILE"
dockerfilePath = "khdn_apps/Dockerfile"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
